/**
 * Reads SVG files from material-icon-theme and generates src/icon-data.ts.
 * Uses a deduplicated registry: unique SVGs are stored once, and
 * extension/filename maps only store the registry key (not the SVG string).
 */

import { generateManifest } from 'material-icon-theme';
import { readFileSync, writeFileSync, existsSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import { createRequire } from 'module';

const __dirname = dirname(fileURLToPath(import.meta.url));
const rootDir = join(__dirname, '..');
const require = createRequire(import.meta.url);

const pkgPath = require.resolve('material-icon-theme/package.json');
const iconsDir = join(dirname(pkgPath), 'icons');

const manifest = generateManifest();

function readSvg(iconPath) {
  const filename = iconPath.split('/').pop();
  const fullPath = join(iconsDir, filename);
  if (!existsSync(fullPath)) return null;
  return readFileSync(fullPath, 'utf-8').trim();
}

function getIconSvgs(iconKey) {
  const def = manifest.iconDefinitions?.[iconKey];
  if (!def?.iconPath) return null;
  const dark = readSvg(def.iconPath);
  if (!dark) return null;

  const lightDef = manifest.iconDefinitions?.[iconKey + '_light'];
  const light = lightDef?.iconPath ? (readSvg(lightDef.iconPath) ?? dark) : dark;
  return { dark, light };
}

// ── Build deduplicated registry ───────────────────────────────────────────────
// registry: iconKey -> { dark, light }
const registry = {};

// extension/filename -> iconKey (just the key, not the SVG)
const extKeys = {};
const nameKeys = {};

for (const [ext, iconKey] of Object.entries(manifest.fileExtensions ?? {})) {
  if (!registry[iconKey]) {
    const svgs = getIconSvgs(iconKey);
    if (svgs) registry[iconKey] = svgs;
  }
  if (registry[iconKey]) extKeys[ext] = iconKey;
}

for (const [name, iconKey] of Object.entries(manifest.fileNames ?? {})) {
  if (!registry[iconKey]) {
    const svgs = getIconSvgs(iconKey);
    if (svgs) registry[iconKey] = svgs;
  }
  if (registry[iconKey]) nameKeys[name] = iconKey;
}

// ── Obsidian-specific extensions not in material-icon-theme ──────────────────
function addCustom(ext, iconFile, customKey) {
  if (registry[customKey]) { extKeys[ext] = customKey; return; }
  const svgPath = join(iconsDir, iconFile);
  if (!existsSync(svgPath)) return;
  const dark = readFileSync(svgPath, 'utf-8').trim();
  registry[customKey] = { dark, light: dark };
  extKeys[ext] = customKey;
}

addCustom('canvas', 'flow.svg', 'flow');
addCustom('base', 'database.svg', 'database');

// ── Default / folder icons ────────────────────────────────────────────────────
const defaultKey = manifest.file ?? 'file';
const folderKey = manifest.folder ?? 'folder';
const folderOpenKey = manifest.folderExpanded ?? 'folder-open';

if (!registry[defaultKey]) registry[defaultKey] = getIconSvgs(defaultKey) ?? { dark: '', light: '' };
if (!registry[folderKey]) registry[folderKey] = getIconSvgs(folderKey) ?? { dark: '', light: '' };
if (!registry[folderOpenKey]) registry[folderOpenKey] = getIconSvgs(folderOpenKey) ?? { dark: '', light: '' };

// ── Emit TypeScript ───────────────────────────────────────────────────────────
const output = `// Auto-generated by scripts/build-icons.mjs — do not edit manually
// Icon source: material-icon-theme (https://github.com/material-extensions/vscode-material-icon-theme)

export interface IconSet {
  dark: string;
  light: string;
}

/** Deduplicated SVG registry — each unique icon is stored exactly once */
export const iconRegistry: Record<string, IconSet> = ${JSON.stringify(registry, null, 2)};

/** Maps file extension -> iconRegistry key */
export const fileExtensionKeys: Record<string, string> = ${JSON.stringify(extKeys, null, 2)};

/** Maps exact filename -> iconRegistry key */
export const fileNameKeys: Record<string, string> = ${JSON.stringify(nameKeys, null, 2)};

export const defaultFileIconKey = ${JSON.stringify(defaultKey)};
export const folderIconKey = ${JSON.stringify(folderKey)};
export const folderOpenIconKey = ${JSON.stringify(folderOpenKey)};
`;

writeFileSync(join(rootDir, 'src/icon-data.ts'), output, 'utf-8');

console.log(
  `✅ Generated src/icon-data.ts\n` +
  `   ${Object.keys(extKeys).length} extension mappings\n` +
  `   ${Object.keys(nameKeys).length} filename mappings\n` +
  `   ${Object.keys(registry).length} unique SVGs (was ${Object.keys(extKeys).length + Object.keys(nameKeys).length} before dedup)`
);
